### ISSUE TITLE
[Feat]: Multiple Team to Repository mapping support

### ISSUE THREAD

**Issue by GeekMasher** [advanced-security/ghas-reviewer-app#42]
### What new feature are you looking for / expect?

A requested feature is the ability to have different teams mapped to different repositories.

This could be done via a configuration file that is passed into the application.

**Here is an example:**

```yaml

teams:
  # This is the default team if nothing matches
  - name: "SecTeam"
    default: true

  - name: "SecTeam1"
    # [optional]
    severity: high
    # [optional] list of repos this team takes care of
    repositories:
      - advanced-security/repo1
      - advanced-security/repo4

  - name: "SecTeam2"
    repositories:
      - advanced-security/repo2
      - advanced-security/repo3

```

### Expectations

Opt-in Feature

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
